### ISSUE TITLE
Feature Request: Show timestamp of utterences.

### ISSUE THREAD

**Issue by genevera** [imdatsolak/katip#8]
Hi!  I use this software all the time to transcribe voice recordings.  I think it would be fabulous if Katip could prepend the audio timestamp (relative to beginning of recording minimally, also in date/time if available)

Keep up the great work :)

**Comment by i-celeste-aurora** [comment]
Great to hear that this small app is helpful. I will try my best to implement the request.

**Comment by genevera** [comment]
Thank you!!

**Comment by i-celeste-aurora** [comment]
It was NOT issue #8 that was deprecated, but rather issue #6 - sorry for confusion. Issue #6 **is** implemented
