### ISSUE TITLE
File transcription stopped after few minutes

### ISSUE THREAD

**Issue by sidan5** [imdatsolak/katip#9]
File transcription stops after around 7 minutes with success although the file have long way to go. This is using macOS Monterey v12.6 (latest). @imdatsolak

**Comment by i-celeste-aurora** [comment]
Is there *any* possibility to provide the file in question? I could then check it over the weekend.

**Comment by sidan5** [comment]
Every file I tried...

**Comment by sidan5** [comment]
@imdatsolak Did you find time to look at that? I have no clue how to solve this. Thanks

**Comment by i-celeste-aurora** [comment]
I just ran a 53-Minute recording without any issues.
Note: the time shown is the estimated DURATION of the transcription-process, it is NOT the length of the audio-file. Please check out the `ETA Estimation` part in the README.

If your machine is really fast, it can transcribe a one-hour audio recording within minutes.
